import type { NextPage } from 'next'
import Head from 'next/head'
import { useAuth } from '../hooks/auth'
import useProducts from '../hooks/use-product'

const Home = () => {
  const { data: products, error, create, remove } = useProducts();
  if (!products) return <div>Loading...</div>
  if (error) return <div>eror</div>
  return (
    <div>
      <Head>
        <title>Next JS | LuvCii</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <form action="" className='my-3 border-rose-400'>
          <input type="text" name="" id="" />

          <button className='py-2 bg-blue-600 w-20' onClick={() => create({ id: 2, name: "Product B" })}>Create</button>
        </form>
        <div>


          <table className="w-1/3 text-center">
            <thead className="border-b bg-gray-800">
              <tr>
                <th scope="col" className="text-sm font-medium text-white px-6 py-4">
                  ID
                </th>
                <th scope="col" className="text-sm font-medium text-white px-6 py-4">
                  NAME
                </th>
                <th scope="col" className="text-sm font-medium text-white px-6 py-4">
                  REMOVE
                </th>

              </tr>
            </thead>
            {products.map((product: any, index: any) => (
              <tbody key={index}>
                <tr className="bg-white border-b">
                  <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">{index + 1}</td>
                  <td className="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                    {product.name}
                  </td>
                  <td className="text-sm text-red-800 font-medium px-6 py-4 whitespace-nowrap">
                    <button onClick={() => remove(product.id)}>Delete</button>
                  </td>

                </tr>

              </tbody>
            ))}
          </table>



        </div>
        HomePage
      </main>
    </div>
  )
}
// Home.Layout = Layout;
export default Home
